### PR TITLE
Fix console account password change

### PR DESCRIPTION
**Pull request by sesposito**
Resolves https://github.com/heroiclabs/nakama/issues/1026.

### CODE REVIEW

**Comment by ahay-agile6** [comment]
Hello! I am the author of #1026 .
I was excited to see this change, so I pulled this branch down locally, built, and ran it.
However, this still does not fix the issue 😭 
Is there a way to test that the password change updates as expected?

Thank you 🙂

**Comment by sesposito** [comment]
Odd, this branch definitely seems to fix it for me, I've tested several times, I'll double check again.

**Comment by sesposito** [comment]
I tested on postgresql myself too and followed the steps in the issue and the password appeared to be set correctly.

**Comment by ahay-agile6** [comment]
Hi again!

I figured out the issue - it was on the Unity side: I was using the `Password` content type of the `InputField` and I was using the value of the display text, which were only asterisks, not of the **`InputField.text`** - so I was only sending "****" and not the real password 😊 

This fix is working both in the Nakama console API explorer and from the Unity client for me!

Thank you so much @sesposito 🙏I really appreciate your time and help.

**Comment by sesposito** [comment]
No worries, I'm glad it's sorted! :)

**Review by zyro — APPROVED** [review]

**Pull request merged**
