### PR TITLE
Console ui Angular 15 upgrade

### PR DESCRIPTION
**Pull request by deflinhec**

### CODE REVIEW

**Comment by sesposito** [comment]
Hello @deflinhec,

Thank you for the PR, we've reviewed it and we'd like to merge it but there's a couple of minor tweaks needed:
1) Where `vanillia-jsoneditor` is used, the input should default to "text".
2) If the storage object is saved editing the content in the "tree" view, it seems to not be working correctly.

We'd also like to extend the use of `vanillia-jsoneditor` to other areas of the UI, but that can be tackled in another PR (by either you or ourselves).

If you could kindly fix these small issues we'd gladly merge this in.

**Comment by deflinhec** [comment]
Sure, thanks for your time, I'll take a look of it.

**Comment by deflinhec** [comment]
All the issues have been resolved.

**Review by zyro — APPROVED** [review]

**Comment by zyro** [comment]
Amazing work @deflinhec! 🙇

**Pull request merged**
