### PR TITLE
Added constants for storage permissions.

### PR DESCRIPTION
**Pull request by volknanebo**
Added constants for storage permissions.

### CODE REVIEW

**Comment by Dimon4eg** [comment]
Why closed?

**Comment by zyro** [comment]
@Dimon4eg Looks like this was a duplicate of https://github.com/heroiclabs/nakama/pull/303.

**Comment by Dimon4eg** [comment]
Oh I see

**Comment by volknanebo** [comment]
I'm trying to implement #181 . I just PR'ed wrong commit .

**Pull request closed without merging**
