### PR TITLE
invalid memory address or nil pointer dereference - lua pcall. (#693)

### PR DESCRIPTION
**Pull request by kavenGw**

### CODE REVIEW

**Comment by kavenGw** [comment]
Description
lua pcall over but luastate is Closed caused by (match stop with call queue is full)

Steps to Reproduce
pcall(nk.storage_write,xxx) in match_loop
a lot of presences join match to trigger call queue is full
Actual Result
server crash

**Comment by ragavendranbala** [comment]
This pull request looks like fix my issue :
https://github.com/heroiclabs/nakama-unity/issues/114
https://github.com/heroiclabs/nakama/issues/636

@kavenGw can you tell me how to build a docker file from this pull request? Thanks in advance

**Comment by kavenGw** [comment]
> This pull request looks like fix my issue : [heroiclabs/nakama-unity#114](https://github.com/heroiclabs/nakama-unity/issues/114) #636
> 
> @kavenGw can you tell me how to build a docker file from this pull request? Thanks in advance

I just read your issue, but I don't think we have the same reason. I'm using Nakama Lua runtime and my issue is caused by one of my matches being stopped by the call queue is full. But there is a DB read in match_loop, the DB read will return failed to the Lua runtime(which the Lua state is already disposed when the match stopped).

Anyway, if you want to try my code. Just use the default docker file. I just change 2 lines.

**Comment by sesposito** [comment]
@kavenGw do you have more info or a stacktrace you could provide on the panic you've observed?

**Comment by zyro** [comment]
Addressed cleanly in 6d8195b99d4c59247e0aa98b92f1c8aa806be19d, stack should only have been `nil` when all match function executions ended.

**Pull request closed without merging**
