### PR TITLE
when ProcessRequest is false and it sends error message to chan, the …

### PR DESCRIPTION
**Pull request by nguyentrannhan**
According to issue https://github.com/heroiclabs/nakama/issues/1164
nakama-js can be timeout because the IncomingLoop is break. We need to add a flag to break IncomingLoop safely

### CODE REVIEW

**Comment by minhlucvan** [comment]
I am facing the same problem, please consider to merge this one

**Comment by mofirouz** [comment]
The PR and code change is not descriptive enough.

- Can you please describe the actual problem you are facing? 
- Can you tell us what the gameplay mechanic you are building?
- What game engine (SDK) and what devices are you targeting? 

I ask these questions because we've never seen an issue in this code path.

**Comment by nguyentrannhan** [comment]
I create this issue https://github.com/heroiclabs/nakama/issues/1164 for describe the problem what I am facing with. Please take a look.
Here is screen shot when I tested with joinChat function

The timeout message will appear after 10 seconds
image

**Comment by zyro** [comment]
There is not enough information provided to understand why the server should process one additional message when an error is encountered with the socket connection.

If you can provide this additional required context then please feel free to re-open this, and we can evaluate it then. A complete minimal reproducible test case would also be very helpful. 🙏

**Comment by nguyentrannhan** [comment]
This PR fix the issue about missing last error message due to the loop is closed. It is helpful to let client know the reason why server close the session.

**Pull request closed without merging**
